const wordPairs = [
    // Original User List
    { civilian: 'Apple', undercover: 'Pear' },
    { civilian: 'Facebook', undercover: 'Twitter' },
    { civilian: 'Pizza', undercover: 'Burger' },
    { civilian: 'Dog', undercover: 'Wolf' },
    { civilian: 'Harry Potter', undercover: 'Lord of the Rings' },
    { civilian: 'Guitar', undercover: 'Violin' },
    { civilian: 'Beach', undercover: 'Desert' },
    { civilian: 'Coffee', undercover: 'Tea' },
    { civilian: 'Batman', undercover: 'Superman' },
    { civilian: 'Summer', undercover: 'Winter' },

    // Expansion 1: Technology & Internet
    { civilian: 'Apple', undercover: 'Microsoft' },
    { civilian: 'Google', undercover: 'Bing' },
    { civilian: 'Instagram', undercover: 'Snapchat' },
    { civilian: 'iPhone', undercover: 'Android' },
    { civilian: 'Laptop', undercover: 'Desktop' },
    { civilian: 'Keyboard', undercover: 'Mouse' },
    { civilian: 'Code', undercover: 'Algorithm' },
    { civilian: 'Hacker', undercover: 'Developer' },
    { civilian: 'Email', undercover: 'Text Message' },
    { civilian: 'Website', undercover: 'Blog' },
    { civilian: 'Cloud', undercover: 'Server' },
    { civilian: 'Wi-Fi', undercover: 'Ethernet' },
    { civilian: 'Robot', undercover: 'Cyborg' },
    { civilian: 'Drone', undercover: 'Satellite' },

    // Expansion 1: Food & Drink
    { civilian: 'Orange', undercover: 'Lemon' },
    { civilian: 'Pasta', undercover: 'Noodles' },
    { civilian: 'Rice', undercover: 'Quinoa' },
    { civilian: 'Sushi', undercover: 'Sashimi' },
    { civilian: 'Bread', undercover: 'Baguette' },
    { civilian: 'Milk', undercover: 'Yogurt' },
    { civilian: 'Cheese', undercover: 'Butter' },
    { civilian: 'Chocolate', undercover: 'Caramel' },
    { civilian: 'Wine', undercover: 'Beer' },
    { civilian: 'Soda', undercover: 'Juice' },
    { civilian: 'Pancake', undercover: 'Waffle' },
    { civilian: 'Cookie', undercover: 'Brownie' },

    // Expansion 1: Animals
    { civilian: 'Cat', undercover: 'Lion' },
    { civilian: 'Bird', undercover: 'Dinosaur' },
    { civilian: 'Fish', undercover: 'Shark' },
    { civilian: 'Horse', undercover: 'Zebra' },
    { civilian: 'Monkey', undercover: 'Gorilla' },
    { civilian: 'Snake', undercover: 'Lizard' },
    { civilian: 'Butterfly', undercover: 'Moth' },
    { civilian: 'Bee', undercover: 'Wasp' },
    { civilian: 'Spider', undercover: 'Scorpion' },
    { civilian: 'Elephant', undercover: 'Mammoth' },
    { civilian: 'Bear', undercover: 'Panda' },
    { civilian: 'Mouse', undercover: 'Rat' },
    { civilian: 'Eagle', undercover: 'Hawk' },
    { civilian: 'Whale', undercover: 'Dolphin' },

    // Expansion 1: Pop Culture & Media
    { civilian: 'Star Wars', undercover: 'Star Trek' },
    { civilian: 'Marvel', undercover: 'DC' },
    { civilian: 'Game of Thrones', undercover: 'Breaking Bad' },
    { civilian: 'Friends', undercover: 'Seinfeld' },
    { civilian: 'The Simpsons', undercover: 'Family Guy' },
    { civilian: 'Mario', undercover: 'Sonic' },
    { civilian: 'Zelda', undercover: 'Final Fantasy' },
    { civilian: 'Monopoly', undercover: 'Chess' },
    { civilian: 'Disney', undercover: 'Pixar' },
    { civilian: 'Taylor Swift', undercover: 'Beyoncé' },
    { civilian: 'Rock', undercover: 'Pop' },
    { civilian: 'Movie', undercover: 'TV Show' },
    { civilian: 'Book', undercover: 'Comic' },

    // Expansion 1: Nature & Geography
    { civilian: 'Mountain', undercover: 'Volcano' },
    { civilian: 'River', undercover: 'Lake' },
    { civilian: 'Ocean', undercover: 'Sea' },
    { civilian: 'Forest', undercover: 'Jungle' },
    { civilian: 'Island', undercover: 'Peninsula' },
    { civilian: 'Rain', undercover: 'Snow' },
    { civilian: 'Sun', undercover: 'Moon' },
    { civilian: 'Star', undercover: 'Planet' },
    { civilian: 'Earth', undercover: 'Mars' },
    { civilian: 'Tree', undercover: 'Flower' },
    { civilian: 'Grass', undercover: 'Moss' },
    { civilian: 'Cloud', undercover: 'Fog' },
    { civilian: 'Tornado', undercover: 'Hurricane' },
    { civilian: 'Cave', undercover: 'Tunnel' },

    // Expansion 1: Objects & Items
    { civilian: 'Piano', undercover: 'Organ' },
    { civilian: 'Car', undercover: 'Motorcycle' },
    { civilian: 'Bicycle', undercover: 'Skateboard' },
    { civilian: 'Boat', undercover: 'Submarine' },
    { civilian: 'Train', undercover: 'Bus' },
    { civilian: 'House', undercover: 'Apartment' },
    { civilian: 'Chair', undercover: 'Sofa' },
    { civilian: 'Table', undercover: 'Desk' },
    { civilian: 'Lamp', undercover: 'Candle' },
    { civilian: 'Book', undercover: 'Magazine' },
    { civilian: 'Pen', undercover: 'Pencil' },
    { civilian: 'Watch', undercover: 'Clock' },
    { civilian: 'Key', undercover: 'Lock' },
    { civilian: 'Coin', undercover: 'Bill' },

    // Expansion 1: Concepts & Abstract
    { civilian: 'Day', undercover: 'Night' },
    { civilian: 'Love', undercover: 'Hate' },
    { civilian: 'Happy', undercover: 'Sad' },
    { civilian: 'Good', undercover: 'Evil' },
    { civilian: 'Peace', undercover: 'War' },
    { civilian: 'Dream', undercover: 'Nightmare' },
    { civilian: 'Art', undercover: 'Science' },
    { civilian: 'Music', undercover: 'Silence' },
    { civilian: 'Past', undercover: 'Future' },
    { civilian: 'Life', undercover: 'Death' },
    { civilian: 'Truth', undercover: 'Lie' },
    { civilian: 'Light', undercover: 'Dark' },
    { civilian: 'Beginning', undercover: 'End' },
    { civilian: 'Order', undercover: 'Chaos' },

    // Expansion 1: Sports & Activities
    { civilian: 'Soccer', undercover: 'Basketball' },
    { civilian: 'Football', undercover: 'Rugby' },
    { civilian: 'Baseball', undercover: 'Cricket' },
    { civilian: 'Tennis', undercover: 'Badminton' },
    { civilian: 'Golf', undercover: 'Mini Golf' },
    { civilian: 'Swimming', undercover: 'Diving' },
    { civilian: 'Running', undercover: 'Sprinting' },
    { civilian: 'Yoga', undercover: 'Pilates' },
    { civilian: 'Skiing', undercover: 'Snowboarding' },
    { civilian: 'Boxing', undercover: 'Karate' },
    { civilian: 'Hiking', undercover: 'Camping' },
    { civilian: 'Fishing', undercover: 'Hunting' },
    { civilian: 'Dancing', undercover: 'Singing' },
    { civilian: 'Painting', undercover: 'Drawing' },
    { civilian: 'Reading', undercover: 'Writing' },

    // Expansion 1: Professions
    { civilian: 'Doctor', undercover: 'Surgeon' },
    { civilian: 'Nurse', undercover: 'Paramedic' },
    { civilian: 'Teacher', undercover: 'Professor' },
    { civilian: 'Police', undercover: 'Detective' },
    { civilian: 'Firefighter', undercover: 'Soldier' },
    { civilian: 'Chef', undercover: 'Baker' },
    { civilian: 'Artist', undercover: 'Musician' },
    { civilian: 'Actor', undercover: 'Director' },
    { civilian: 'Writer', undercover: 'Journalist' },
    { civilian: 'Scientist', undercover: 'Engineer' },
    { civilian: 'Lawyer', undercover: 'Judge' },
    { civilian: 'Pilot', undercover: 'Astronaut' },
    { civilian: 'Farmer', undercover: 'Gardener' },
    { civilian: 'Architect', undercover: 'Designer' },
    { civilian: 'Plumber', undercover: 'Electrician' },

    // Expansion 1: Clothing & Fashion
    { civilian: 'Shirt', undercover: 'Blouse' },
    { civilian: 'Pants', undercover: 'Jeans' },
    { civilian: 'Shoes', undercover: 'Boots' },
    { civilian: 'Hat', undercover: 'Cap' },
    { civilian: 'Jacket', undercover: 'Coat' },
    { civilian: 'Socks', undercover: 'Stockings' },
    { civilian: 'Gloves', undercover: 'Mittens' },
    { civilian: 'Scarf', undercover: 'Tie' },
    { civilian: 'Dress', undercover: 'Skirt' },
    { civilian: 'Ring', undercover: 'Necklace' },
    { civilian: 'Bracelet', undercover: 'Anklet' },
    { civilian: 'Glasses', undercover: 'Sunglasses' },
    { civilian: 'T-shirt', undercover: 'Sweater' },
    { civilian: 'Shorts', undercover: 'Capris' },
    { civilian: 'Suit', undercover: 'Tuxedo' },

    // Expansion 1: Places & Buildings
    { civilian: 'School', undercover: 'University' },
    { civilian: 'Hospital', undercover: 'Clinic' },
    { civilian: 'Library', undercover: 'Bookstore' },
    { civilian: 'Museum', undercover: 'Art Gallery' },
    { civilian: 'Restaurant', undercover: 'Cafe' },
    { civilian: 'Hotel', undercover: 'Motel' },
    { civilian: 'Airport', undercover: 'Train Station' },
    { civilian: 'Bank', undercover: 'Post Office' },
    { civilian: 'Church', undercover: 'Temple' },
    { civilian: 'Castle', undercover: 'Palace' },
    { civilian: 'Stadium', undercover: 'Arena' },
    { civilian: 'Mall', undercover: 'Market' },
    { civilian: 'Farm', undercover: 'Ranch' },
    { civilian: 'Office', undercover: 'Factory' },
    { civilian: 'Theater', undercover: 'Cinema' },

    // Expansion 1: Body Parts
    { civilian: 'Hand', undercover: 'Foot' },
    { civilian: 'Eye', undercover: 'Ear' },
    { civilian: 'Nose', undercover: 'Mouth' },
    { civilian: 'Head', undercover: 'Shoulder' },
    { civilian: 'Arm', undercover: 'Leg' },
    { civilian: 'Finger', undercover: 'Toe' },
    { civilian: 'Heart', undercover: 'Brain' },
    { civilian: 'Lungs', undercover: 'Stomach' },
    { civilian: 'Bone', undercover: 'Muscle' },
    { civilian: 'Hair', undercover: 'Nail' },
    { civilian: 'Tooth', undercover: 'Tongue' },
    { civilian: 'Knee', undercover: 'Elbow' },
    { civilian: 'Skin', undercover: 'Blood' },
    { civilian: 'Back', undercover: 'Chest' },
    { civilian: 'Vein', undercover: 'Artery' },

    // Expansion 1: Fantasy & Mythology
    { civilian: 'Dragon', undercover: 'Unicorn' },
    { civilian: 'Wizard', undercover: 'Witch' },
    { civilian: 'Elf', undercover: 'Dwarf' },
    { civilian: 'Goblin', undercover: 'Orc' },
    { civilian: 'Ghost', undercover: 'Zombie' },
    { civilian: 'Vampire', undercover: 'Werewolf' },
    { civilian: 'Angel', undercover: 'Demon' },
    { civilian: 'Fairy', undercover: 'Gnome' },
    { civilian: 'Mermaid', undercover: 'Siren' },
    { civilian: 'Zeus', undercover: 'Odin' },
    { civilian: 'Hercules', undercover: 'Thor' },
    { civilian: 'Magic', undercover: 'Potion' },
    { civilian: 'Sword', undercover: 'Shield' },
    { civilian: 'Castle', undercover: 'Dungeon' },
    { civilian: 'King', undercover: 'Queen' },

    // Expansion 1: Brands
    { civilian: 'Nike', undercover: 'Adidas' },
    { civilian: "McDonald's", undercover: 'Burger King' },
    { civilian: 'Coca-Cola', undercover: 'Pepsi' },
    { civilian: 'Ford', undercover: 'Toyota' },
    { civilian: 'Lego', undercover: 'Play-Doh' },
    { civilian: 'IKEA', undercover: 'Walmart' },
    { civilian: 'Amazon', undercover: 'eBay' },
    { civilian: 'Netflix', undercover: 'Hulu' },
    { civilian: 'Spotify', undercover: 'Apple Music' },
    { civilian: 'Starbucks', undercover: "Dunkin' Donuts" },
    { civilian: 'Gucci', undercover: 'Prada' },
    { civilian: 'Rolex', undercover: 'Omega' },
    { civilian: 'Ferrari', undercover: 'Lamborghini' },
    { civilian: 'Samsung', undercover: 'LG' },
    { civilian: 'Visa', undercover: 'Mastercard' },
    
    // Expansion 1: Miscellaneous
    { civilian: 'Fire', undercover: 'Ice' },
    { civilian: 'Water', undercover: 'Air' },
    { civilian: 'Gold', undercover: 'Silver' },
    { civilian: 'Diamond', undercover: 'Ruby' },
    { civilian: 'Bridge', undercover: 'Tunnel' },
    { civilian: 'Road', undercover: 'Path' },
    { civilian: 'Mirror', undercover: 'Window' },
    { civilian: 'Door', undercover: 'Gate' },
    { civilian: 'Cup', undercover: 'Mug' },
    { civilian: 'Plate', undercover: 'Bowl' },
    { civilian: 'Fork', undercover: 'Spoon' },
    { civilian: 'Knife', undercover: 'Axe' },
    { civilian: 'Rope', undercover: 'Chain' },
    { civilian: 'Paper', undercover: 'Cardboard' },
    { civilian: 'Paint', undercover: 'Ink' },

    // Expansion 2: Verbs & Actions
    { civilian: 'Walk', undercover: 'Run' },
    { civilian: 'Talk', undercover: 'Whisper' },
    { civilian: 'Eat', undercover: 'Devour' },
    { civilian: 'Sleep', undercover: 'Hibernate' },
    { civilian: 'Jump', undercover: 'Leap' },
    { civilian: 'Push', undercover: 'Shove' },
    { civilian: 'Pull', undercover: 'Yank' },
    { civilian: 'Throw', undercover: 'Hurl' },
    { civilian: 'Catch', undercover: 'Snatch' },
    { civilian: 'Laugh', undercover: 'Giggle' },
    { civilian: 'Cry', undercover: 'Sob' },
    { civilian: 'Think', undercover: 'Ponder' },
    { civilian: 'Look', undercover: 'Stare' },
    { civilian: 'Build', undercover: 'Construct' },
    { civilian: 'Break', undercover: 'Shatter' },
    { civilian: 'Fly', undercover: 'Glide' },
    { civilian: 'Swim', undercover: 'Float' },
    { civilian: 'Climb', undercover: 'Ascend' },
    { civilian: 'Fall', undercover: 'Tumble' },
    { civilian: 'Start', undercover: 'Begin' },

    // Expansion 2: Adjectives & Descriptors
    { civilian: 'Big', undercover: 'Huge' },
    { civilian: 'Small', undercover: 'Tiny' },
    { civilian: 'Hot', undercover: 'Scorching' },
    { civilian: 'Cold', undercover: 'Freezing' },
    { civilian: 'Fast', undercover: 'Rapid' },
    { civilian: 'Slow', undercover: 'Sluggish' },
    { civilian: 'Bright', undercover: 'Dazzling' },
    { civilian: 'Dark', undercover: 'Murky' },
    { civilian: 'Old', undercover: 'Ancient' },
    { civilian: 'New', undercover: 'Modern' },
    { civilian: 'Hard', undercover: 'Solid' },
    { civilian: 'Soft', undercover: 'Spongy' },
    { civilian: 'Quiet', undercover: 'Silent' },
    { civilian: 'Loud', undercover: 'Deafening' },
    { civilian: 'Easy', undercover: 'Simple' },
    { civilian: 'Wet', undercover: 'Soaked' },
    { civilian: 'Dry', undercover: 'Arid' },
    { civilian: 'Rich', undercover: 'Wealthy' },
    { civilian: 'Poor', undercover: 'Broke' },
    { civilian: 'Strong', undercover: 'Powerful' },

    // Expansion 2: Tools & Equipment
    { civilian: 'Hammer', undercover: 'Mallet' },
    { civilian: 'Screwdriver', undercover: 'Wrench' },
    { civilian: 'Saw', undercover: 'Chainsaw' },
    { civilian: 'Drill', undercover: 'Auger' },
    { civilian: 'Pliers', undercover: 'Tongs' },
    { civilian: 'Shovel', undercover: 'Spade' },
    { civilian: 'Ladder', undercover: 'Stool' },
    { civilian: 'Nail', undercover: 'Screw' },
    { civilian: 'Bolt', undercover: 'Nut' },
    { civilian: 'Tape', undercover: 'Glue' },
    { civilian: 'Compass', undercover: 'Protractor' },
    { civilian: 'Microscope', undercover: 'Telescope' },
    { civilian: 'Camera', undercover: 'Binoculars' },
    { civilian: 'Helmet', undercover: 'Shield' },
    { civilian: 'Anchor', undercover: 'Hook' },

    // Expansion 2: School Subjects & Academics
    { civilian: 'Math', undercover: 'Physics' },
    { civilian: 'Chemistry', undercover: 'Biology' },
    { civilian: 'History', undercover: 'Geography' },
    { civilian: 'Literature', undercover: 'Poetry' },
    { civilian: 'Algebra', undercover: 'Calculus' },
    { civilian: 'Grammar', undercover: 'Vocabulary' },
    { civilian: 'Essay', undercover: 'Thesis' },
    { civilian: 'Exam', undercover: 'Quiz' },
    { civilian: 'Homework', undercover: 'Project' },
    { civilian: 'Diploma', undercover: 'Degree' },
    { civilian: 'Student', undercover: 'Scholar' },
    { civilian: 'Library', undercover: 'Archive' },
    { civilian: 'Science', undercover: 'Philosophy' },
    { civilian: 'Economics', undercover: 'Sociology' },
    { civilian: 'Psychology', undercover: 'Anthropology' },

    // Expansion 2: Shapes & Colors
    { civilian: 'Red', undercover: 'Maroon' },
    { civilian: 'Blue', undercover: 'Navy' },
    { civilian: 'Green', undercover: 'Emerald' },
    { civilian: 'Yellow', undercover: 'Gold' },
    { civilian: 'Orange', undercover: 'Amber' },
    { civilian: 'Purple', undercover: 'Violet' },
    { civilian: 'Black', undercover: 'Charcoal' },
    { civilian: 'White', undercover: 'Ivory' },
    { civilian: 'Circle', undercover: 'Sphere' },
    { civilian: 'Square', undercover: 'Cube' },
    { civilian: 'Triangle', undercover: 'Pyramid' },
    { civilian: 'Rectangle', undercover: 'Box' },
    { civilian: 'Star', undercover: 'Hexagon' },
    { civilian: 'Oval', undercover: 'Ellipse' },
    { civilian: 'Line', undercover: 'Curve' },

    // Expansion 2: Holidays & Celebrations
    { civilian: 'Christmas', undercover: 'Easter' },
    { civilian: 'Halloween', undercover: 'Thanksgiving' },
    { civilian: "New Year's", undercover: 'Christmas Eve' },
    { civilian: 'Birthday', undercover: 'Anniversary' },
    { civilian: "Valentine's Day", undercover: 'Wedding' },
    { civilian: 'Parade', undercover: 'Festival' },
    { civilian: 'Party', undercover: 'Gala' },
    { civilian: 'Gift', undercover: 'Present' },
    { civilian: 'Cake', undercover: 'Pie' },
    { civilian: 'Fireworks', undercover: 'Confetti' },
    { civilian: 'Vacation', undercover: 'Holiday' },
    { civilian: 'Carnival', undercover: 'Circus' },
    { civilian: 'Feast', undercover: 'Banquet' },
    { civilian: 'Tradition', undercover: 'Custom' },
    { civilian: 'Celebration', undercover: 'Ceremony' },

    // Expansion 2: Materials & Substances
    { civilian: 'Wood', undercover: 'Metal' },
    { civilian: 'Stone', undercover: 'Brick' },
    { civilian: 'Glass', undercover: 'Plastic' },
    { civilian: 'Cotton', undercover: 'Silk' },
    { civilian: 'Wool', undercover: 'Leather' },
    { civilian: 'Paper', undercover: 'Parchment' },
    { civilian: 'Clay', undercover: 'Porcelain' },
    { civilian: 'Water', undercover: 'Oil' },
    { civilian: 'Air', undercover: 'Gas' },
    { civilian: 'Iron', undercover: 'Steel' },
    { civilian: 'Copper', undercover: 'Bronze' },
    { civilian: 'Sand', undercover: 'Soil' },
    { civilian: 'Chalk', undercover: 'Graphite' },
    { civilian: 'Wax', undercover: 'Gel' },
    { civilian: 'Powder', undercover: 'Dust' },

    // Expansion 2: Countries & Cities
    { civilian: 'USA', undercover: 'Canada' },
    { civilian: 'China', undercover: 'Japan' },
    { civilian: 'France', undercover: 'Germany' },
    { civilian: 'Italy', undercover: 'Spain' },
    { civilian: 'UK', undercover: 'Australia' },
    { civilian: 'Brazil', undercover: 'Argentina' },
    { civilian: 'India', undercover: 'Pakistan' },
    { civilian: 'Russia', undercover: 'Ukraine' },
    { civilian: 'Egypt', undercover: 'Greece' },
    { civilian: 'New York', undercover: 'Los Angeles' },
    { civilian: 'London', undercover: 'Paris' },
    { civilian: 'Tokyo', undercover: 'Beijing' },
    { civilian: 'Rome', undercover: 'Athens' },
    { civilian: 'Sydney', undercover: 'Melbourne' },
    { civilian: 'Moscow', undercover: 'Berlin' },

    // Expansion 2: Hobbies & Crafts
    { civilian: 'Knitting', undercover: 'Crochet' },
    { civilian: 'Sewing', undercover: 'Embroidery' },
    { civilian: 'Gardening', undercover: 'Bonsai' },
    { civilian: 'Cooking', undercover: 'Baking' },
    { civilian: 'Photography', undercover: 'Videography' },
    { civilian: 'Pottery', undercover: 'Sculpting' },
    { civilian: 'Calligraphy', undercover: 'Typography' },
    { civilian: 'Origami', undercover: 'Kirigami' },
    { civilian: 'Stamp Collecting', undercover: 'Coin Collecting' },
    { civilian: 'Bird Watching', undercover: 'Stargazing' },
    { civilian: 'Journaling', undercover: 'Scrapbooking' },
    { civilian: 'Meditation', undercover: 'Tai Chi' },
    { civilian: 'Board Games', undercover: 'Card Games' },
    { civilian: 'Magic Tricks', undercover: 'Juggling' },
    { civilian: 'Whittling', undercover: 'Carving' },

    // Expansion 2: Science & Nature (Advanced)
    { civilian: 'Atom', undercover: 'Molecule' },
    { civilian: 'Cell', undercover: 'Organism' },
    { civilian: 'DNA', undercover: 'RNA' },
    { civilian: 'Gravity', undercover: 'Magnetism' },
    { civilian: 'Evolution', undercover: 'Genetics' },
    { civilian: 'Photosynthesis', undercover: 'Respiration' },
    { civilian: 'Fossil', undercover: 'Amber' },
    { civilian: 'Glacier', undercover: 'Iceberg' },
    { civilian: 'Comet', undercover: 'Asteroid' },
    { civilian: 'Galaxy', undercover: 'Nebula' },
    { civilian: 'Tectonic Plate', undercover: 'Volcano' },
    { civilian: 'Ecosystem', undercover: 'Biome' },
    { civilian: 'Species', undercover: 'Genus' },
    { civilian: 'Vaccine', undercover: 'Antibiotic' },
    { civilian: 'Element', undercover: 'Compound' },
    { civilian: 'Acid', undercover: 'Base' },
    { civilian: 'Quark', undercover: 'Lepton' },
    { civilian: 'Black Hole', undercover: 'Supernova' },
    { civilian: 'Light Year', undercover: 'Parsec' },
    { civilian: 'Herbivore', undercover: 'Carnivore' },

    // Expansion 2: More Animals
    { civilian: 'Frog', undercover: 'Toad' },
    { civilian: 'Turtle', undercover: 'Tortoise' },
    { civilian: 'Alligator', undercover: 'Crocodile' },
    { civilian: 'Rabbit', undercover: 'Hare' },
    { civilian: 'Goat', undercover: 'Sheep' },
    { civilian: 'Chicken', undercover: 'Turkey' },
    { civilian: 'Penguin', undercover: 'Puffin' },
    { civilian: 'Owl', undercover: 'Falcon' },
    { civilian: 'Fox', undercover: 'Coyote' },
    { civilian: 'Deer', undercover: 'Elk' },
    { civilian: 'Porcupine', undercover: 'Hedgehog' },
    { civilian: 'Ostrich', undercover: 'Emu' },
    { civilian: 'Llama', undercover: 'Alpaca' },
    { civilian: 'Jaguar', undercover: 'Leopard' },
    { civilian: 'Bison', undercover: 'Buffalo' },

    // Expansion 2: More Food
    { civilian: 'Taco', undercover: 'Burrito' },
    { civilian: 'Salad', undercover: 'Coleslaw' },
    { civilian: 'Steak', undercover: 'Pork Chop' },
    { civilian: 'Bacon', undercover: 'Sausage' },
    { civilian: 'Muffin', undercover: 'Scone' },
    { civilian: 'Donut', undercover: 'Croissant' },
    { civilian: 'Whiskey', undercover: 'Rum' },
    { civilian: 'Ketchup', undercover: 'Salsa' },
    { civilian: 'Salt', undercover: 'Pepper' },
    { civilian: 'Sugar', undercover: 'Stevia' },
    { civilian: 'Cinnamon', undercover: 'Nutmeg' },
    { civilian: 'Garlic', undercover: 'Onion' },
    { civilian: 'Lemonade', undercover: 'Iced Tea' },
    { civilian: 'Espresso', undercover: 'Latte' },
    { civilian: 'Cheddar', undercover: 'Mozzarella' },

    // Expansion 3: Feelings & Emotions
    { civilian: 'Joy', undercover: 'Ecstasy' },
    { civilian: 'Anger', undercover: 'Rage' },
    { civilian: 'Fear', undercover: 'Terror' },
    { civilian: 'Surprise', undercover: 'Shock' },
    { civilian: 'Calm', undercover: 'Serene' },
    { civilian: 'Anxious', undercover: 'Nervous' },
    { civilian: 'Brave', undercover: 'Courageous' },
    { civilian: 'Shy', undercover: 'Timid' },
    { civilian: 'Proud', undercover: 'Arrogant' },
    { civilian: 'Humble', undercover: 'Modest' },
    { civilian: 'Curious', undercover: 'Inquisitive' },
    { civilian: 'Bored', undercover: 'Apathetic' },
    { civilian: 'Excited', undercover: 'Thrilled' },
    { civilian: 'Confused', undercover: 'Bewildered' },
    { civilian: 'Hope', undercover: 'Optimism' },

    // Expansion 3: Time & Calendar
    { civilian: 'Second', undercover: 'Moment' },
    { civilian: 'Minute', undercover: 'Hour' },
    { civilian: 'Day', undercover: 'Week' },
    { civilian: 'Month', undercover: 'Year' },
    { civilian: 'Decade', undercover: 'Century' },
    { civilian: 'Morning', undercover: 'Afternoon' },
    { civilian: 'Evening', undercover: 'Midnight' },
    { civilian: 'Dawn', undercover: 'Dusk' },
    { civilian: 'Present', undercover: 'Now' },
    { civilian: 'Monday', undercover: 'Friday' },
    { civilian: 'January', undercover: 'June' },
    { civilian: 'Spring', undercover: 'Autumn' },
    { civilian: 'Sunrise', undercover: 'Sunset' },
    { civilian: 'Today', undercover: 'Tomorrow' },
    { civilian: 'Yesterday', undercover: 'Today' },

    // Expansion 3: More Transportation
    { civilian: 'Car', undercover: 'Truck' },
    { civilian: 'Bus', undercover: 'Van' },
    { civilian: 'Scooter', undercover: 'Moped' },
    { civilian: 'Rollerblades', undercover: 'Ice Skates' },
    { civilian: 'Helicopter', undercover: 'Airplane' },
    { civilian: 'Jet', undercover: 'Rocket' },
    { civilian: 'Battleship', undercover: 'Aircraft Carrier' },
    { civilian: 'Canoe', undercover: 'Kayak' },
    { civilian: 'Ferry', undercover: 'Cruise Ship' },
    { civilian: 'Taxi', undercover: 'Uber' },
    { civilian: 'Ambulance', undercover: 'Fire Truck' },
    { civilian: 'Spaceship', undercover: 'Shuttle' },
    { civilian: 'Tractor', undercover: 'Combine' },
    { civilian: 'Limousine', undercover: 'Sedan' },
    { civilian: 'Convertible', undercover: 'Coupe' },

    // Expansion 3: More Musical Instruments
    { civilian: 'Drum', undercover: 'Cymbal' },
    { civilian: 'Flute', undercover: 'Clarinet' },
    { civilian: 'Trumpet', undercover: 'Trombone' },
    { civilian: 'Saxophone', undercover: 'Oboe' },
    { civilian: 'Cello', undercover: 'Double Bass' },
    { civilian: 'Ukulele', undercover: 'Mandolin' },
    { civilian: 'Banjo', undercover: 'Harp' },
    { civilian: 'Accordion', undercover: 'Harmonica' },
    { civilian: 'Xylophone', undercover: 'Marimba' },
    { civilian: 'Synthesizer', undercover: 'Keyboard' },
    { civilian: 'Tambourine', undercover: 'Maracas' },
    { civilian: 'Bagpipes', undercover: 'Didgeridoo' },
    { civilian: 'French Horn', undercover: 'Tuba' },
    { civilian: 'Triangle', undercover: 'Gong' },
    { civilian: 'Electric Guitar', undercover: 'Acoustic Guitar' },

    // Expansion 3: Government & Society
    { civilian: 'President', undercover: 'Prime Minister' },
    { civilian: 'King', undercover: 'Emperor' },
    { civilian: 'Democracy', undercover: 'Monarchy' },
    { civilian: 'Republic', undercover: 'Dictatorship' },
    { civilian: 'Senate', undercover: 'Parliament' },
    { civilian: 'Mayor', undercover: 'Governor' },
    { civilian: 'Law', undercover: 'Regulation' },
    { civilian: 'Tax', undercover: 'Toll' },
    { civilian: 'Vote', undercover: 'Election' },
    { civilian: 'Citizen', undercover: 'Resident' },
    { civilian: 'Capital', undercover: 'Metropolis' },
    { civilian: 'Nation', undercover: 'Country' },
    { civilian: 'Army', undercover: 'Navy' },
    { civilian: 'Police', undercover: 'Sheriff' },
    { civilian: 'Constitution', undercover: 'Treaty' },

    // Expansion 3: The Kitchen
    { civilian: 'Oven', undercover: 'Microwave' },
    { civilian: 'Blender', undercover: 'Mixer' },
    { civilian: 'Toaster', undercover: 'Kettle' },
    { civilian: 'Fridge', undercover: 'Freezer' },
    { civilian: 'Sink', undercover: 'Dishwasher' },
    { civilian: 'Spatula', undercover: 'Whisk' },
    { civilian: 'Ladle', undercover: 'Tongs' },
    { civilian: 'Grater', undercover: 'Peeler' },
    { civilian: 'Cutting Board', undercover: 'Rolling Pin' },
    { civilian: 'Pot', undercover: 'Pan' },
    { civilian: 'Cabinet', undercover: 'Pantry' },
    { civilian: 'Spice', undercover: 'Herb' },
    { civilian: 'Flour', undercover: 'Sugar' },
    { civilian: 'Vinegar', undercover: 'Oil' },
    { civilian: 'Apron', undercover: 'Oven Mitt' },

    // Expansion 3: The Natural World (Advanced)
    { civilian: 'Peninsula', undercover: 'Archipelago' },
    { civilian: 'Strait', undercover: 'Channel' },
    { civilian: 'Plateau', undercover: 'Mesa' },
    { civilian: 'Canyon', undercover: 'Gorge' },
    { civilian: 'Dune', undercover: 'Oasis' },
    { civilian: 'Estuary', undercover: 'Delta' },
    { civilian: 'Monsoon', undercover: 'Drought' },
    { civilian: 'Aurora', undercover: 'Eclipse' },
    { civilian: 'Stalactite', undercover: 'Stalagmite' },
    { civilian: 'Magma', undercover: 'Lava' },
    { civilian: 'Bedrock', undercover: 'Sediment' },
    { civilian: 'Pollen', undercover: 'Nectar' },
    { civilian: 'Spore', undercover: 'Seed' },
    { civilian: 'Fungus', undercover: 'Algae' },
    { civilian: 'Predator', undercover: 'Prey' },

    // Expansion 3: Clothing Accessories
    { civilian: 'Belt', undercover: 'Suspenders' },
    { civilian: 'Wallet', undercover: 'Purse' },
    { civilian: 'Bowtie', undercover: 'Necktie' },
    { civilian: 'Cufflinks', undercover: 'Tie Clip' },
    { civilian: 'Brooch', undercover: 'Pin' },
    { civilian: 'Handkerchief', undercover: 'Pocket Square' },
    { civilian: 'Beret', undercover: 'Fedora' },
    { civilian: 'Visor', undercover: 'Headband' },
    { civilian: 'Earmuffs', undercover: 'Headphones' },
    { civilian: 'Watch', undercover: 'Fitbit' },
    { civilian: 'Backpack', undercover: 'Briefcase' },
    { civilian: 'Umbrella', undercover: 'Parasol' },
    { civilian: 'Cane', undercover: 'Walking Stick' },
    { civilian: 'Goggles', undercover: 'Mask' },
    { civilian: 'Sandals', undercover: 'Flip-flops' },

    // Expansion 3: Literature & Writing
    { civilian: 'Novel', undercover: 'Novella' },
    { civilian: 'Chapter', undercover: 'Verse' },
    { civilian: 'Prologue', undercover: 'Epilogue' },
    { civilian: 'Protagonist', undercover: 'Antagonist' },
    { civilian: 'Metaphor', undercover: 'Simile' },
    { civilian: 'Noun', undercover: 'Verb' },
    { civilian: 'Adjective', undercover: 'Adverb' },
    { civilian: 'Punctuation', undercover: 'Spelling' },
    { civilian: 'Fiction', undercover: 'Non-fiction' },
    { civilian: 'Biography', undercover: 'Autobiography' },
    { civilian: 'Fable', undercover: 'Myth' },
    { civilian: 'Comedy', undercover: 'Tragedy' },
    { civilian: 'Sonnet', undercover: 'Haiku' },
    { civilian: 'Manuscript', undercover: 'Scroll' },
    { civilian: 'Author', undercover: 'Narrator' },

    // Expansion 3: More Abstract Concepts
    { civilian: 'Cause', undercover: 'Effect' },
    { civilian: 'Problem', undercover: 'Solution' },
    { civilian: 'Question', undercover: 'Answer' },
    { civilian: 'Theory', undercover: 'Hypothesis' },
    { civilian: 'Fact', undercover: 'Opinion' },
    { civilian: 'Reality', undercover: 'Illusion' },
    { civilian: 'Freedom', undercover: 'Captivity' },
    { civilian: 'Justice', undercover: 'Injustice' },
    { civilian: 'Success', undercover: 'Failure' },
    { civilian: 'Strength', undercover: 'Weakness' },
    { civilian: 'Knowledge', undercover: 'Ignorance' },
    { civilian: 'Beauty', undercover: 'Ugliness' },
    { civilian: 'Logic', undercover: 'Emotion' },
    { civilian: 'Skill', undercover: 'Talent' },
    { civilian: 'Risk', undercover: 'Reward' },

    // Expansion 3: More Pop Culture
    { civilian: 'The Beatles', undercover: 'The Rolling Stones' },
    { civilian: 'Michael Jackson', undercover: 'Prince' },
    { civilian: 'Leonardo da Vinci', undercover: 'Michelangelo' },
    { civilian: 'Shakespeare', undercover: 'Chaucer' },
    { civilian: 'Einstein', undercover: 'Newton' },
    { civilian: 'Sherlock Holmes', undercover: 'Hercule Poirot' },
    { civilian: 'James Bond', undercover: 'Jason Bourne' },
    { civilian: 'Indiana Jones', undercover: 'Lara Croft' },
    { civilian: 'Minecraft', undercover: 'Roblox' },
    { civilian: 'Call of Duty', undercover: 'Battlefield' },
    { civilian: 'Pokémon', undercover: 'Digimon' },
    { civilian: 'The Office (US)', undercover: 'Parks and Recreation' },
    { civilian: 'Alien', undercover: 'Predator' },
    { civilian: 'The Godfather', undercover: 'Goodfellas' },
    { civilian: 'Titanic', undercover: 'Avatar' },

    // Expansion 3: Buildings & Architecture
    { civilian: 'Skyscraper', undercover: 'Tower' },
    { civilian: 'Cottage', undercover: 'Mansion' },
    { civilian: 'Cabin', undercover: 'Lodge' },
    { civilian: 'Warehouse', undercover: 'Hangar' },
    { civilian: 'Cathedral', undercover: 'Chapel' },
    { civilian: 'Lighthouse', undercover: 'Windmill' },
    { civilian: 'Pyramid', undercover: 'Ziggurat' },
    { civilian: 'Amphitheater', undercover: 'Colosseum' },
    { civilian: 'Aqueduct', undercover: 'Viaduct' },
    { civilian: 'Fountain', undercover: 'Statue' },
    { civilian: 'Garage', undercover: 'Shed' },
    { civilian: 'Balcony', undercover: 'Terrace' },
    { civilian: 'Basement', undercover: 'Attic' },
    { civilian: 'Hallway', undercover: 'Corridor' },
    { civilian: 'Elevator', undercover: 'Escalator' },

    // Expansion 3: Medical & Anatomy
    { civilian: 'Artery', undercover: 'Capillary' },
    { civilian: 'Neuron', undercover: 'Synapse' },
    { civilian: 'Skull', undercover: 'Spine' },
    { civilian: 'Ribs', undercover: 'Pelvis' },
    { civilian: 'Femur', undercover: 'Humerus' },
    { civilian: 'Tendon', undercover: 'Ligament' },
    { civilian: 'Cornea', undercover: 'Retina' },
    { civilian: 'Virus', undercover: 'Bacteria' },
    { civilian: 'X-Ray', undercover: 'MRI' },
    { civilian: 'Scalpel', undercover: 'Syringe' },
    { civilian: 'Bandage', undercover: 'Gauze' },
    { civilian: 'Stethoscope', undercover: 'Thermometer' },
    { civilian: 'Pill', undercover: 'Capsule' },
    { civilian: 'Anesthesia', undercover: 'Sedative' },
    { civilian: 'Diagnosis', undercover: 'Prognosis' },

    // Expansion 3: The Arts
    { civilian: 'Sculpture', undercover: 'Statue' },
    { civilian: 'Mosaic', undercover: 'Fresco' },
    { civilian: 'Ballet', undercover: 'Tap Dance' },
    { civilian: 'Opera', undercover: 'Musical' },
    { civilian: 'Orchestra', undercover: 'Choir' },
    { civilian: 'Sonnet', undercover: 'Limerick' },
    { civilian: 'Canvas', undercover: 'Easel' },
    { civilian: 'Sketch', undercover: 'Blueprint' },
    { civilian: 'Photography', undercover: 'Cinematography' },
    { civilian: 'Director', undercover: 'Producer' },
    { civilian: 'Comedy', undercover: 'Drama' },
    { civilian: 'Abstract', undercover: 'Realism' },
    { civilian: 'Impressionism', undercover: 'Cubism' },
    { civilian: 'Symphony', undercover: 'Concerto' },
    { civilian: 'Act', undercover: 'Scene' },

    // Expansion 3: Around the House
    { civilian: 'Rug', undercover: 'Carpet' },
    { civilian: 'Curtain', undercover: 'Blinds' },
    { civilian: 'Pillow', undercover: 'Cushion' },
    { civilian: 'Blanket', undercover: 'Duvet' },
    { civilian: 'Bookshelf', undercover: 'Cabinet' },
    { civilian: 'Vase', undercover: 'Pot' },
    { civilian: 'Broom', undercover: 'Mop' },
    { civilian: 'Vacuum', undercover: 'Dustpan' },
    { civilian: 'Towel', undercover: 'Washcloth' },
    { civilian: 'Soap', undercover: 'Shampoo' },
    { civilian: 'Toothbrush', undercover: 'Toothpaste' },
    { civilian: 'Mirror', undercover: 'Scale' },
    { civilian: 'Alarm Clock', undercover: 'Radio' },
    { civilian: 'Television', undercover: 'Remote' },
    { civilian: 'Couch', undercover: 'Loveseat' },

    // Expansion 4: Fictional Characters
    { civilian: 'Dracula', undercover: 'Frankenstein' },
    { civilian: 'Mickey Mouse', undercover: 'Bugs Bunny' },
    { civilian: 'SpongeBob', undercover: 'Patrick' },
    { civilian: 'Homer Simpson', undercover: 'Peter Griffin' },
    { civilian: 'Winnie the Pooh', undercover: 'Paddington Bear' },
    { civilian: 'Godzilla', undercover: 'King Kong' },
    { civilian: 'Cinderella', undercover: 'Snow White' },
    { civilian: 'Peter Pan', undercover: 'Aladdin' },
    { civilian: 'Darth Vader', undercover: 'Joker' },
    { civilian: 'Gandalf', undercover: 'Dumbledore' },
    { civilian: 'Katniss Everdeen', undercover: 'Hermione Granger' },
    { civilian: 'Tony Stark', undercover: 'Bruce Wayne' },
    { civilian: 'Spiderman', undercover: 'Iron Man' },
    { civilian: 'Captain America', undercover: 'Thor' },
    { civilian: 'Wonder Woman', undercover: 'Captain Marvel' },
    { civilian: 'Shrek', undercover: 'Donkey' },
    { civilian: 'Optimus Prime', undercover: 'Megatron' },
    { civilian: 'Pikachu', undercover: 'Charizard' },
    { civilian: 'Don Quixote', undercover: 'Sancho Panza' },
    { civilian: 'Robin Hood', undercover: 'Zorro' },

    // Expansion 4: World Landmarks
    { civilian: 'Eiffel Tower', undercover: 'Statue of Liberty' },
    { civilian: 'Great Wall of China', undercover: 'Colosseum' },
    { civilian: 'Pyramids of Giza', undercover: 'Stonehenge' },
    { civilian: 'Taj Mahal', undercover: 'Machu Picchu' },
    { civilian: 'Big Ben', undercover: 'Leaning Tower of Pisa' },
    { civilian: 'Sydney Opera House', undercover: 'Christ the Redeemer' },
    { civilian: 'Mount Rushmore', undercover: 'Golden Gate Bridge' },
    { civilian: 'St. Basil\'s Cathedral', undercover: 'Brandenburg Gate' },
    { civilian: 'Acropolis', undercover: 'Parthenon' },
    { civilian: 'Niagara Falls', undercover: 'Victoria Falls' },
    { civilian: 'Grand Canyon', undercover: 'Mount Everest' },
    { civilian: 'Louvre Museum', undercover: 'British Museum' },
    { civilian: 'Neuschwanstein Castle', undercover: 'Edinburgh Castle' },
    { civilian: 'Burj Khalifa', undercover: 'Empire State Building' },
    { civilian: 'Petra', undercover: 'Chichen Itza' },
    { civilian: 'Angkor Wat', undercover: 'Borobudur' },
    { civilian: 'The Kremlin', undercover: 'The White House' },
    { civilian: 'Forbidden City', undercover: 'Buckingham Palace' },
    { civilian: 'Sagrada Familia', undercover: 'Notre Dame' },
    { civilian: 'Easter Island', undercover: 'Galapagos Islands' },

    // Expansion 4: Historical Events
    { civilian: 'World War I', undercover: 'World War II' },
    { civilian: 'American Revolution', undercover: 'French Revolution' },
    { civilian: 'Renaissance', undercover: 'Reformation' },
    { civilian: 'Industrial Revolution', undercover: 'Information Age' },
    { civilian: 'The Cold War', undercover: 'The Space Race' },
    { civilian: 'The Great Depression', undercover: 'The Roaring Twenties' },
    { civilian: 'The Roman Empire', undercover: 'The British Empire' },
    { civilian: 'The Middle Ages', undercover: 'The Dark Ages' },
    { civilian: 'The Crusades', undercover: 'The Inquisition' },
    { civilian: 'The Black Death', undercover: 'The Spanish Flu' },
    { civilian: 'The Titanic Sinking', undercover: 'The Hindenburg Disaster' },
    { civilian: 'The Moon Landing', undercover: 'The Fall of the Berlin Wall' },
    { civilian: 'The Reformation', undercover: 'The Enlightenment' },
    { civilian: 'The Viking Age', undercover: 'The Age of Discovery' },
    { civilian: 'The Silk Road', undercover: 'The Spice Trade' },
    { civilian: 'The Gold Rush', undercover: 'The Oregon Trail' },
    { civilian: 'The Civil Rights Movement', undercover: 'The Women\'s Suffrage Movement' },
    { civilian: 'The Protestant Reformation', undercover: 'The Counter-Reformation' },
    { civilian: 'The Norman Conquest', undercover: 'The Battle of Hastings' },
    { civilian: 'The Cuban Missile Crisis', undercover: 'The Vietnam War' },

    // Expansion 4: Computer Science
    { civilian: 'Variable', undercover: 'Function' },
    { civilian: 'Loop', undercover: 'Conditional' },
    { civilian: 'Array', undercover: 'Object' },
    { civilian: 'Boolean', undercover: 'String' },
    { civilian: 'Integer', undercover: 'Float' },
    { civilian: 'Class', undercover: 'Instance' },
    { civilian: 'Compiler', undercover: 'Interpreter' },
    { civilian: 'Frontend', undercover: 'Backend' },
    { civilian: 'Database', undercover: 'API' },
    { civilian: 'Cache', undercover: 'Cookie' },
    { civilian: 'Git', undercover: 'SVN' },
    { civilian: 'Bug', undercover: 'Feature' },
    { civilian: 'Firewall', undercover: 'VPN' },
    { civilian: 'Pixel', undercover: 'Vector' },
    { civilian: 'CPU', undercover: 'GPU' },
    { civilian: 'RAM', undercover: 'ROM' },
    { civilian: 'TCP', undercover: 'UDP' },
    { civilian: 'HTML', undercover: 'CSS' },
    { civilian: 'JavaScript', undercover: 'Python' },
    { civilian: 'Linux', undercover: 'Windows' },

    // Expansion 4: Business & Finance
    { civilian: 'Stock', undercover: 'Bond' },
    { civilian: 'Debit', undercover: 'Credit' },
    { civilian: 'Asset', undercover: 'Liability' },
    { civilian: 'Profit', undercover: 'Loss' },
    { civilian: 'Revenue', undercover: 'Expense' },
    { civilian: 'Bull Market', undercover: 'Bear Market' },
    { civilian: 'Capitalism', undercover: 'Socialism' },
    { civilian: 'Inflation', undercover: 'Deflation' },
    { civilian: 'Mortgage', undercover: 'Loan' },
    { civilian: 'Shareholder', undercover: 'Stakeholder' },
    { civilian: 'CEO', undercover: 'CFO' },
    { civilian: 'Marketing', undercover: 'Sales' },
    { civilian: 'Startup', undercover: 'Corporation' },
    { civilian: 'Investment', undercover: 'Savings' },
    { civilian: 'Bitcoin', undercover: 'Ethereum' },
    { civilian: 'Supply', undercover: 'Demand' },
    { civilian: 'Monopoly', undercover: 'Oligopoly' },
    { civilian: 'Recession', undercover: 'Depression' },
    { civilian: 'Budget', undercover: 'Forecast' },
    { civilian: 'Invoice', undercover: 'Receipt' },

    // Expansion 4: Car Parts
    { civilian: 'Engine', undercover: 'Transmission' },
    { civilian: 'Tire', undercover: 'Wheel' },
    { civilian: 'Brake', undercover: 'Accelerator' },
    { civilian: 'Steering Wheel', undercover: 'Gear Shift' },
    { civilian: 'Headlight', undercover: 'Taillight' },
    { civilian: 'Windshield', undercover: 'Sunroof' },
    { civilian: 'Bumper', undercover: 'Fender' },
    { civilian: 'Exhaust', undercover: 'Muffler' },
    { civilian: 'Spark Plug', undercover: 'Piston' },
    { civilian: 'Radiator', undercover: 'Coolant' },
    { civilian: 'Battery', undercover: 'Alternator' },
    { civilian: 'Axle', undercover: 'Suspension' },
    { civilian: 'Glove Box', undercover: 'Trunk' },
    { civilian: 'Seatbelt', undercover: 'Airbag' },
    { civilian: 'Clutch', undercover: 'Flywheel' },
    { civilian: 'Fuel Tank', undercover: 'Fuel Injector' },
    { civilian: 'Wiper Blade', undercover: 'Side Mirror' },
    { civilian: 'License Plate', undercover: 'VIN' },
    { civilian: 'Carburetor', undercover: 'Catalytic Converter' },
    { civilian: 'Chassis', undercover: 'Frame' },

    // Expansion 4: Scientific Fields
    { civilian: 'Astronomy', undercover: 'Astrology' },
    { civilian: 'Geology', undercover: 'Paleontology' },
    { civilian: 'Botany', undercover: 'Zoology' },
    { civilian: 'Ecology', undercover: 'Meteorology' },
    { civilian: 'Anatomy', undercover: 'Physiology' },
    { civilian: 'Genetics', undercover: 'Immunology' },
    { civilian: 'Volcanology', undercover: 'Seismology' },
    { civilian: 'Oceanography', undercover: 'Hydrology' },
    { civilian: 'Kinesiology', undercover: 'Neurology' },
    { civilian: 'Mycology', undercover: 'Virology' },
    { civilian: 'Ornithology', undercover: 'Entomology' },
    { civilian: 'Cosmology', undercover: 'Quantum Mechanics' },
    { civilian: 'Thermodynamics', undercover: 'Electromagnetism' },
    { civilian: 'Acoustics', undercover: 'Optics' },
    { civilian: 'Robotics', undercover: 'Artificial Intelligence' },
    { civilian: 'Linguistics', undercover: 'Etymology' },
    { civilian: 'Archaeology', undercover: 'Genealogy' },
    { civilian: 'Criminology', undercover: 'Forensics' },
    { civilian: 'Toxicology', undercover: 'Pharmacology' },
    { civilian: 'Pathology', undercover: 'Epidemiology' },

    // Expansion 4: Space & Astronomy
    { civilian: 'Orbit', undercover: 'Rotation' },
    { civilian: 'Constellation', undercover: 'Asterism' },
    { civilian: 'Meteor', undercover: 'Meteorite' },
    { civilian: 'Solar System', undercover: 'Milky Way' },
    { civilian: 'Dwarf Planet', undercover: 'Moon' },
    { civilian: 'Red Giant', undercover: 'White Dwarf' },
    { civilian: 'Pulsar', undercover: 'Quasar' },
    { civilian: 'Gravity', undercover: 'Dark Matter' },
    { civilian: 'Big Bang', undercover: 'Singularity' },
    { civilian: 'Wormhole', undercover: 'Black Hole' },
    { civilian: 'Equinox', undercover: 'Solstice' },
    { civilian: 'Light Speed', undercover: 'Warp Speed' },
    { civilian: 'Zenith', undercover: 'Nadir' },
    { civilian: 'Apogee', undercover: 'Perigee' },
    { civilian: 'Asteroid Belt', undercover: 'Kuiper Belt' },
    { civilian: 'Cosmic Rays', undercover: 'Solar Wind' },
    { civilian: 'Exoplanet', undercover: 'Habitable Zone' },
    { civilian: 'Hubble Telescope', undercover: 'James Webb Telescope' },
    { civilian: 'NASA', undercover: 'SpaceX' },
    { civilian: 'Probe', undercover: 'Rover' }
];
